apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgvector
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"pgvector:latest","namespace":"NAMESPACE_PLACEHOLDER"},"fieldPath":"spec.template.spec.containers[?(@.name==\"pgvector\")].image","paused":false}]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgvector
  template:
    spec:
      serviceAccountName: pgvector-sa
      securityContext:
        runAsUser: 0
      containers:
        - name: pgvector
          image: image-registry.openshift-image-registry.svc:5000/NAMESPACE_PLACEHOLDER/pgvector
          ports:
            - containerPort: 5432
              protocol: TCP
          envFrom:
            - secretRef:
                name: pgvector-secrets
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgvector-data


