kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: agent-os-api
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'agent-os-api:latest'
  strategy:
    type: Docker
  source:
    type: Git
    git:
      uri: "https://github.com/ajshedivy/agentos-openshift-template.git"
      ref: main
    contextDir: /
  triggers:
    - type: ConfigChange


